# fly.toml app configuration file generated for minify-backend on 2025-03-16T14:37:27Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'minify-backend'
primary_region = 'ams'

[build]
  dockerfile = "Dockerfile"  # Specify the Dockerfile path here

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 2048
